lora-aprs/LoRa_APRS_Tracker

src/LoRa_APRS_Tracker.cpp
src/settings.h

Next Beacon Time is nice to have on display. To have some space i moved GPS date and time into one line.
Battery voltage and (dis)charge current can be easily obtained vom AXP chip.

Display next beacon time and battery voltage and (dis)charge current

---

src/LoRa_APRS_Tracker.cpp
src/settings.h

add some manual configure in setting.h because many country have different frequency allocation

Add manual FREQ, SF, CR, BW config

---

src/LoRa_APRS_Tracker.cpp

Change Filename in Error Message when missing tracker.json config File

Change Errormessage when config is missing

---

data/tracker.json
src/LoRa_APRS_Tracker.cpp
src/configuration.cpp
src/configuration.h

```
io_pin: any free io Pin
start_delay: PTT Tail Time in ms before starting Lora transmission
end_delay: PTT Hang Time in ms after ending Lora transmission
reverse: Tx = LOW, Rx = HIGH
```

Added PTT Output for external Amplifier

---

src/LoRa_APRS_Tracker.cpp
src/power_management.cpp
src/power_management.h

Sbias master

---

src/LoRa_APRS_Tracker.cpp

colon as time separator, more space between date and time

---

src/LoRa_APRS_Tracker.cpp

Something I found useful (at least for myself) is this tweak: it logs when the GPS-fix status changes.
Feel free not to merge if you don't like it :-)

log GPS state (GPS-fix)

---

README.md

This may help some users to easily upload firmware to the board.

add steps to install on linux

---

platformio.ini

Bump ArduinoJson from 6.20.1 to 6.21.2

Bump ArduinoJson from 6.20.1 to 6.21.2

---

.clang-format
platformio.ini
src/LoRa_APRS_Tracker.cpp
src/pins.h
src/power_management.cpp
src/power_management.h

closing https://github.com/lora-aprs/LoRa_APRS_Tracker/issues/106

add T-Beam v1.2 AXP2101

---

platformio.ini

Bump espressif32 from 6.0.1 to 6.3.2

Bump espressif32 from 6.0.1 to 6.3.2

---

platformio.ini

Bump Adafruit GFX Library from 1.11.5 to 1.11.7

Bump Adafruit GFX Library from 1.11.5 to 1.11.7

---

platformio.ini

Bump espressif32 from 6.3.2 to 6.4.0

Bump espressif32 from 6.3.2 to 6.4.0

---

platformio.ini

Bump ArduinoJson from 6.21.2 to 6.21.3

Bump ArduinoJson from 6.21.2 to 6.21.3

---

src/power_management.cpp

fixing https://github.com/lora-aprs/LoRa_APRS_Tracker/issues/121

quick fix for axp2101 charging

---

src/LoRa_APRS_Tracker.cpp

https://github.com/lora-aprs/LoRa_APRS_Tracker/issues/124

fix division by zero (current speed)

---

platformio.ini

Bump XPowersLib from 0.1.8 to 0.2.4

Bump XPowersLib from 0.1.8 to 0.2.4

---

platformio.ini

Bump Adafruit GFX Library from 1.11.7 to 1.11.9

Bump Adafruit GFX Library from 1.11.7 to 1.11.9

---

platformio.ini

Bump ArduinoJson from 6.21.3 to 7.0.4

Bump ArduinoJson from 6.21.3 to 7.0.4

---

platformio.ini

Bump espressif32 from 6.4.0 to 6.7.0

Bump espressif32 from 6.4.0 to 6.7.0

---

platformio.ini

Bump TinyGPSPlus from 1.0.3 to 1.1.0

Bump TinyGPSPlus from 1.0.3 to 1.1.0
